-- ALLO TABLESPACE

1	ALLOCATION_CONTROLS				2476 rows affected
2	ALLOCATION_KEYS					1185 rows affected
3	ALLOCATION_FIXED_AMOUNTS		0 rows affected
4	ALLOCATION_LINES				4090 rows affected
5	ALLOCATION_OUCS					7892 rows affected
6	ALLOCATION_SBUS					7605 rows affected
7	ALLOCATION_PRODUCTS				0 rows affected
8	ALLOCATION_UNIT_COSTS			0 rows affected
9	ALLOCATION_VARIABLE_KEYS		1981 rows affected
10	ALLOCATION_VAR_KEY_OUCS			1777 rows affected
11	ALLOCATION_VAR_KEY_SBUS			4471 rows affected
12	ALLOCATION_VAR_KEY_PROD			0 rows affected
13	ALLOCATION_DATA_SETS			0 rows affected
  

		 /* ALLOCATION DATA*/ 

---Get data from MGT (mr Hung share)---
SELECT /*+ Leading (t3 t2 t1 t5) parallel(10) */
T5.OUC_ATTRIBUTE_02,
T2.VISION_OUC,
T2.MRL_LINE,
T2.RESULT_SOURCE,
SUM (BALANCE_05)
FROM MGT_RESULT_HEADERS T2,
MGT_RESULT_BALANCES T3,
(SELECT *
FROM MRL_EXPANDED T1
WHERE T1.BAL_TYPE IN (3)) T1,
OUC_CODES T5
WHERE T2.YEAR = T3.YEAR
AND T2.DATA_SOURCE = T3.DATA_SOURCE
AND T2.SEQUENCE_MR = T3.SEQUENCE_MR
AND T1.SOURCE_MRL_LINE = T2.MRL_LINE
AND T1.SOURCE_BAL_TYPE = T3.BAL_TYPE
AND T2.YEAR = 2021
---AND T2.Vision_SBU IN ('OB', 'OP')
AND T2.DATA_SOURCE = 'A'
AND T1.SOURCE_TYPE IN (0)
AND T1.MRL_ATTRIBUTE_06 = 'MA06300' --- Cost
---AND T1.MRL_LINE NOT IN ('M625020')---remove MRL
AND T2.VISION_OUC = T5.VISION_OUC
AND T5.OUC_ATTRIBUTE_02 IN ('OA020115') --Parameter
AND T2.PL_GL NOT LIKE '52%'
GROUP BY T5.OUC_ATTRIBUTE_02, T2.VISION_OUC, T2.MRL_LINE,T2.RESULT_SOURCE


SELECT * 
 FROM 
     TRANS_COUNT_HISTORY_HEADERS T1,
     TRANS_COUNT_HISTORY_BALANCES T2 ,
     TRANSACTION_CODE_GROUPS T3
     WHERE 
     T1.YEAR = T2.YEAR
     AND T1.SEQUENCE_TH = T2.SEQUENCE_TH
     AND T2.BAL_TYPE = 11
     AND T2.YEAR IN ('2018' ) 
                AND T1.MRL_LINE     = 'MT10070'
     AND T1.TRANSACTION_CODE_GROUP=T3.TRANSACTION_CODE_GROUP 
     GROUP BY  T3.TRANS_CODE_GROUP_DESC

 
-- refresh MGT_RESULT_2021

DROP TABLE MGT_RESULT_2021 PURGE
/

CREATE TABLE MGT_RESULT_2021
NOLOGGING
PARALLEL 
TABLESPACE VISION_DATA_FTP_AUDIT 
AS
   SELECT T2.YEAR,
          T2.SEQUENCE_MR,
          --T2.DATA_SOURCE,
          COUNTRY,
          LE_BOOK,
          CUSTOMER_ID,
          GL_ENRICH_ID,
          CONTRACT_ID,
          BS_GL,
          PL_GL,
          VISION_OUC,
          VISION_SBU,
          ACCOUNT_OFFICER,
          COST_CENTER,
          CURRENCY,
          MIS_CURRENCY,
          T2.MRL_LINE,
          PRODUCT,
          RESULT_SOURCE,
          MGT_REFERENCE,
          ORIGINAL_OUC,
          RECORD_TYPE,
          SOURCE_ID,
          T3.BAL_TYPE,
          BALANCE_01,
          BALANCE_02,
          BALANCE_03,
          BALANCE_04,
          BALANCE_05,
          BALANCE_06,
          BALANCE_07,
          BALANCE_08,
          BALANCE_09,
          BALANCE_10,
          BALANCE_11,
          BALANCE_12,
          --BALANCE_YTD,
          --MGT_LINE_LEVEL,
          MGT_LINE,
          MGT_LINE_DESCRIPTION,
          MGT_TYPE,
          CASE
             WHEN MGT_LINE IN ('G011441', 'G011663')
             THEN
                'LOAN'
             WHEN MGT_LINE IN ('G012331')
             THEN
                'CASA'
             WHEN MGT_LINE IN ('G012335', 'G012440')
             THEN
                'FD'
             WHEN MGT_LINE IN ('G015100',
                               'G015200',
                               'G015205',
                               'G015410',
                               'G015510',
                               'G015520',
                               'G015530',
                               'G015540',
                               'G015610')
             THEN
                'NFI'
             WHEN     BS_GL LIKE '9%'
                  AND PL_GL = '555555555'
                  AND COST_CENTER = 'LC'
             THEN 'LC'
             WHEN     BS_GL LIKE '9%'
                  AND PL_GL = '555555555'
                  AND COST_CENTER = 'BG'
             THEN
                'BG'
             ELSE
                NULL
          END
             MGT_GROUP
     FROM MGT_RESULT_HEADERS T2,
          MGT_RESULT_BALANCES T3,
          (SELECT *
             FROM MGT_EXPANDED T1
            WHERE     T1.MGT_LINE_LEVEL = 1
                  AND MGT_LINE != 'G010000'
                  AND T1.SOURCE_TYPE IN (0)
                  AND T1.BAL_TYPE IN (1,
                                      2,
                                      3,
                                      4)) T1
    WHERE     T2.YEAR = T3.YEAR
          AND T2.DATA_SOURCE = T3.DATA_SOURCE
          AND T2.SEQUENCE_MR = T3.SEQUENCE_MR
          AND T2.MRL_LINE = T1.SOURCE_MRL_LINE(+)
          AND T3.BAL_TYPE = T1.SOURCE_BAL_TYPE(+)
          AND T2.YEAR = 2021
          AND T2.DATA_SOURCE = 'A'
/

DROP TABLE ALLOCATION_RESULTS_202101 PURGE
/
CREATE TABLE ALLOCATION_RESULTS_202101 NOLOGGING PARALLEL COMPRESS FOR ALL OPERATIONS
TABLESPACE VISION_DATA_FTP_AUDIT AS 
SELECT   * FROM ALLOCATION_RESULTS
/
TRUNCATE TABLE ALLOCATION_RESULTS
/
DROP TABLE MGT_COUNT_202101 PURGE
/
CREATE TABLE MGT_COUNT_202101 NOLOGGING PARALLEL   
 TABLESPACE VISION_DATA_BACKUP AS 
SELECT   * FROM MGT_COUNT WHERE YEAR=2021 --AND COUNT_01<>0 --change
/

DROP TABLE ALLOCATION_SOURCE_DETAILS_202101 PURGE
/
CREATE TABLE ALLOCATION_SOURCE_DETAILS_202101 NOLOGGING PARALLEL   
 TABLESPACE VISION_DATA_BACKUP AS 
SELECT   * FROM ALLOCATION_SOURCE_DETAILS WHERE YEAR=2021 --AND MONTH= 10 --change
/
TRUNCATE TABLE ALLOCATION_SOURCE_DETAILS
/



-- Allocation Report

DROP TABLE TEMP_ALL_COST PURGE
/

CREATE TABLE   TEMP_ALL_COST  NOLOGGING PARALLEL    AS 
SELECT /*+PARALLEL(30)*/ 
TYPE,ALLOCATION_DESCRIPTION,MAPPING,
     MGT_LINE,MGT_LINE_DESCRIPTION,MGT_TYPE,A.MRL_LINE,  MRL_DESCRIPTION, RESULT_SOURCE,
     METHOD,A.MGT_REFERENCE,LEVEL1,
     CASE WHEN A.MRL_LINE IN ('M641440','M641027','M641033','M625140','M627060','M631090',
'M627120','M631020','M631080','M640045','M640610','M641034',
'M641110','M641115','M641250','M641230','M641270','M627020',
'M641010','M641051','M642062','M627070','M627080','M640010',
'M625020','M627010','M627030','M627040','M642061','M642064',
'M642063','M642067','M571030','M623100','M623200','M625021',
'M651020','M651030','M625025','M627110','M631010','M631060',
'M640620','M631030','M631050','M640050','M641009','M641030',
'M641210','M641240','M641410','M641018','M621100','M641054',
'M641063','M641120','M641155','M641060','M641069','M641003',
'M641015','M642060','M625040','M625110','M627050','M631040',
'M631070','M680020','M680010','M680095','M680085','M680090',
'M680100','M681010','M681020','M681030','M681040','M681050',
'M681060','M681070','M681080','M680015','M680025','M680050',
'M680060','M680080','M680070','M680075','M680065','M681450',
'M681460','M681420','M681410','M681440','M681430','M680055',
'M680045','M681360','M681350','M681380','M681370','M681400',
'M681390','M681500','M681490','M681055','M681045','M681090',
'M681200','M681220','M681210','M681240','M681230','M681280',
'M681270','M681300','M681290','M681320','M681310','M681340',
'M681330','M681480','M681470')
THEN A.MRL_LINE ELSE NULL END MRL_COST_CHECK,
     MRL_ATT_06_DESCRIPTION ATT_COST_CHECK,
     A.VISION_SBU,
     PARENT_SBU_DESCRIPTION BU,
     OUC_ATTRIBUTE_02 ATT_02,  OUC_ATT_02_DESCRIPTION ATT_02_DESC,OUC_ATTRIBUTE_12 ATT_12,  OUC_ATT_12_DESCRIPTION ATT_12_DESC,
     OUC_ATT_13_DESCRIPTION REGION,OUC_ATT_14_DESCRIPTION BRN, 
     SUBSTR(A.VISION_OUC,-4,4)CC,
     SUBSTR(A.VISION_OUC, 5,4)OUC,
     SUM (BALANCE_12) COST, --change*****************************
     SUM (CASE 
     WHEN MGT_REFERENCE= '2045'  AND A.VISION_SBU='RB' THEN BALANCE_12
     WHEN (MGT_REFERENCE||A.MRL_LINE) <> (TO_CHAR(SEQ)||RECEIVER_MRL)
        AND TYPE IS NOT NULL THEN BALANCE_12 ELSE 0 END )SENT ,--change
     SUM (CASE 
     WHEN MGT_REFERENCE= '2045'  AND A.VISION_SBU<>'RB' THEN BALANCE_12
     WHEN (MGT_REFERENCE||A.MRL_LINE) = (TO_CHAR(SEQ)||RECEIVER_MRL)
        AND TYPE IS NOT NULL THEN BALANCE_12 ELSE 0 END )REC--change
FROM MGT_RESULT_2021 A, VISION_SBU B, VW_ALLOCATION_CONFIG Q,
(SELECT * FROM MRL_EXPANDED 
WHERE SOURCE_BAL_TYPE=3
AND SOURCE_TYPE=0) W ,OUC_EXPANDED D
WHERE     A.BAL_TYPE = 3
     AND MGT_TYPE = 60
     AND A.VISION_SBU = B.VISION_SBU
     AND A.MRL_LINE=W.SOURCE_MRL_LINE (+)
     AND TO_CHAR(A.MGT_REFERENCE )= TO_CHAR(Q.SEQ(+))
     AND A.VISION_OUC=D.VISION_OUC  
GROUP BY MGT_LINE,
     MGT_LINE_DESCRIPTION,
     MGT_TYPE,
     RESULT_SOURCE,
     A.VISION_SBU,MAPPING,LEVEL1,
     PARENT_SBU_DESCRIPTION,A.MRL_LINE,  MRL_DESCRIPTION,MRL_ATT_06_DESCRIPTION,
     METHOD,OUC_ATTRIBUTE_02,  OUC_ATT_02_DESCRIPTION,SUBSTR(A.VISION_OUC,-4,4),TYPE,OUC_ATTRIBUTE_12,  SUBSTR(A.VISION_OUC, 5,4),
     OUC_ATT_13_DESCRIPTION,OUC_ATT_14_DESCRIPTION,OUC_ATT_12_DESCRIPTION,TYPE,ALLOCATION_DESCRIPTION,A.MGT_REFERENCE
      /  
      
       
	  
	  
--COST

CREATE TABLE COST_MRL NOLOGGING PARALLEL AS 
SELECT SOURCE_MRL_LINE
FROM MRL_EXPANDED T1
WHERE T1.BAL_TYPE IN (3)
AND T1.MRL_ATTRIBUTE_06 = 'MA06300' 

 

-- SSC

  SELECT ALLOCATION_DESCRIPTION,
         SEQ,
         A.VISION_OUC,
         RESULT_SOURCE,
         SUM (BALANCE_05)
    FROM MGT_RESULT_202107 A,
         (  SELECT MAX (SEQ) SEQ,
                   MAX (ALLOCATION_DESCRIPTION) ALLOCATION_DESCRIPTION,
                   FROM_OUC
              FROM VW_ALLOCATION_CONFIG
             WHERE TYPE = 'SSC' AND FROM_OUC LIKE 'OA02%'
          GROUP BY FROM_OUC) B,
         OUC_EXPANDED C
   WHERE     A.VISION_OUC = C.VISION_OUC
         AND OUC_ATTRIBUTE_02 = FROM_OUC
         AND BAL_TYPE = 3
GROUP BY A.VISION_OUC,
         RESULT_SOURCE,
         ALLOCATION_DESCRIPTION,
         SEQ
  HAVING SUM (BALANCE_05) <> 0

-- IDC A EXCL RCC

  SELECT ALLOCATION_DESCRIPTION, SEQ, SUM (BALANCE_05) QTTBC_Q
    FROM MGT_RESULT_202107 A,
         (  SELECT MAX (SEQ) SEQ,
                   MAX (ALLOCATION_DESCRIPTION) ALLOCATION_DESCRIPTION,
                   FROM_OUC
              FROM VW_ALLOCATION_CONFIG
             WHERE TYPE = 'IDC ' AND FROM_OUC LIKE 'OA02%' AND METHOD = 'A'
          GROUP BY FROM_OUC) B,
         OUC_EXPANDED C
   WHERE     A.VISION_OUC = C.VISION_OUC
         AND OUC_ATTRIBUTE_02 = FROM_OUC
         AND BAL_TYPE = 3
         AND BALANCE_05 <> 0
         AND EXISTS (SELECT 1 FROM COST_MRL
         WHERE MRL_LINE=SOURCE_MRL_LINE)
GROUP BY ALLOCATION_DESCRIPTION, SEQ
  HAVING SUM (BALANCE_05) <> 0
ORDER BY 2

 
        
-- Check all datasets

SELECT /*+PARALLEL(3)*/ * FROM  
ALLOCATION_CONTROLS WHERE ALLOCATION_SEQUENCE  NOT IN (
SELECT /*+PARALLEL(3)*/ ALLOCATION_SEQUENCE FROM ALLOCATION_DATA_SETS WHERE YEAR=2021)
AND YEAR=2021

  
  --- MGT count
  
  SELECT MRL_LINE,( SELECT MRL_DESCRIPTION FROM MRL_LINES X WHERE X.MRL_LINE=A.MRL_LINE  ) MRL_DESCRIPTION,
BAL_TYPE,
SUM(COUNT_06) 
 FROM MGT_COUNT A
WHERE YEAR=2021
AND COUNT_06<>0
GROUP BY MRL_LINE,BAL_TYPE

SELECT ALLOCATION_DESCRIPTION, SEQ, A.VISION_OUC, RESULT_SOURCE,MRL_LINE, SUM (BALANCE_06) QTTBC_Q
    FROM MGT_RESULT_2021 A,
         (  SELECT MAX (SEQ) SEQ,
                   MAX (ALLOCATION_DESCRIPTION) ALLOCATION_DESCRIPTION,
                   FROM_OUC
              FROM VW_ALLOCATION_CONFIG
             WHERE TYPE = 'IDC ' AND FROM_OUC LIKE 'OA020188%' --AND METHOD = 'A'
          GROUP BY FROM_OUC) B,
         OUC_EXPANDED C
   WHERE     A.VISION_OUC = C.VISION_OUC
         AND OUC_ATTRIBUTE_02 = FROM_OUC
         AND BAL_TYPE = 3
         AND BALANCE_06 <> 0
         AND EXISTS (SELECT 1 FROM COST_MRL
         WHERE MRL_LINE=SOURCE_MRL_LINE)
GROUP BY ALLOCATION_DESCRIPTION, SEQ, A.VISION_OUC, RESULT_SOURCE,MRL_LINE
  HAVING SUM (BALANCE_06) <> 0
ORDER BY VISION_OUC DESC

----ALLOPCM

/* Formatted on 9/4/2021 9:54:22 AM (QP5 v5.252.13127.32867) */
  SELECT T1.YEAR,
         T1.ALLOCATION_MGT_REFERENCE,
         'A' || T1.ALLOCATION_SEQUENCE MA_INPUT_TYPE,
         T4.BATCH_SEQUENCE,
         T2.LEGAL_VEHICLE,
         T1.MONTH,
         T1.DATA_SOURCE,
         T1.Contract_Id,
         T1.Customer_Id,
         T1.ACCOUNT_OFFICER,
         T1.RECEIVE_OUC,
         T1.RECEIVE_SBU,
         T1.RECEIVE_PRODUCT,
         T1.MIS_CURRENCY,
         T1.MRL_LINE,
         T1.BAL_TYPE,
         T3.MA_SEQUENCE,
         T5.MAX_MA_SEQUENCE,
         SUM (ROUND (T1.AMOUNT, 5)) AMOUNT
    FROM ALLOCATION_RESULTS T1,
         ALLOCATION_CONTROLS T2,
         (SELECT T1.YEAR,
                 T1.MGT_REFERENCE,
                 T2.Contract_Id,
                 T2.Customer_Id,
                 T2.ACCOUNT_OFFICER,
                 T2.VISION_OUC,
                 T2.VISION_SBU,
                 T2.PRODUCT,
                 T2.MRL_LINE,
                 T2.MIS_CURRENCY,
                 T2.MA_INPUT_TYPE,
                 T2.MA_SEQUENCE
            FROM MGT_HEADERS T1, MGT_DETAILS T2
           WHERE     T1.YEAR = T2.YEAR(+)
                 AND T1.MGT_REFERENCE = T2.MGT_REFERENCE(+)
                 AND T1.MGT_HEADERS_STATUS = 40) T3,
         MGT_HEADERS T4,
         (  SELECT YEAR, MGT_REFERENCE, MAX (MA_SEQUENCE) MAX_MA_SEQUENCE
              FROM MGT_DETAILS
          GROUP BY YEAR, MGT_REFERENCE) T5
   WHERE     T1.YEAR = T2.YEAR
         AND T1.ALLOCATION_SEQUENCE = T2.ALLOCATION_SEQUENCE
         AND T1.YEAR = T4.YEAR
         AND T1.ALLOCATION_MGT_REFERENCE = T4.MGT_REFERENCE
         AND T1.YEAR = T3.YEAR(+)
         AND T1.ALLOCATION_MGT_REFERENCE = T3.MGT_REFERENCE(+)
         AND T1.Contract_Id = T3.Contract_Id(+)
         AND T1.Customer_Id = T3.Customer_Id(+)
         AND T1.ACCOUNT_OFFICER = T3.ACCOUNT_OFFICER(+)
         AND T1.RECEIVE_OUC = T3.VISION_OUC(+)
         AND T1.RECEIVE_SBU = T3.VISION_SBU(+)
         AND T1.RECEIVE_PRODUCT = T3.PRODUCT(+)
         AND T1.MIS_CURRENCY = T3.MIS_CURRENCY(+)
         AND T1.MRL_LINE = T3.MRL_LINE(+)
         AND ('A' || T1.ALLOCATION_SEQUENCE) = T3.MA_INPUT_TYPE(+)
         AND T1.YEAR = T5.YEAR(+)
         AND TO_CHAR (T1.MGT_REFERENCE) = T5.MGT_REFERENCE(+)
         AND T1.DATA_SOURCE = 'A'
         AND T1.YEAR = 2021
         AND T1.MONTH = 7
         AND T4.MGT_HEADERS_STATUS = 40
         AND T2.ALLOCATION_STATUS = 0
GROUP BY T1.YEAR,
         T1.ALLOCATION_MGT_REFERENCE,
         'A' || T1.ALLOCATION_SEQUENCE,
         T4.BATCH_SEQUENCE,
         T2.LEGAL_VEHICLE,
         T1.MONTH,
         T1.DATA_SOURCE,
         T1.Contract_Id,
         T1.Customer_Id,
         T1.Account_Officer,
         T1.RECEIVE_OUC,
         T1.RECEIVE_SBU,
         T1.RECEIVE_PRODUCT,
         T1.MIS_CURRENCY,
         T1.MRL_LINE,
         T1.BAL_TYPE,
         T3.MA_SEQUENCE,
         T5.MAX_MA_SEQUENCE
ORDER BY T1.YEAR,
         T1.DATA_SOURCE,
         T1.ALLOCATION_MGT_REFERENCE,
         MA_INPUT_TYPE,
         T4.BATCH_SEQUENCE,
         T2.LEGAL_VEHICLE,
         T1.Contract_Id,
         T1.Customer_Id,
         T1.Account_Officer,
         T1.RECEIVE_OUC,
         T1.RECEIVE_SBU,
         T1.RECEIVE_PRODUCT,
         T1.MIS_CURRENCY,
         T1.MRL_LINE,
         T1.BAL_TYPE
		 
		 
		 
		 Dear Team,
Updated CIF level allocation for B and Segment level allocation for FI-001. 
Let me know if you have further queries. 

--SSC

SELECT CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC,SUM(AMOUNT) FROM ALLOCATION_RESULTS_202109 A, VW_ALLOCATION_CONFIG B
WHERE A.ALLOCATION_SEQUENCE =B.SEQ
AND TYPE='SSC'
AND METHOD='W'
AND ALLOCATION_SEQUENCE ='3241'
GROUP BY CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC


--IDC

SELECT CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC,SUM(AMOUNT) FROM ALLOCATION_RESULTS_202109 A, VW_ALLOCATION_CONFIG B
WHERE A.ALLOCATION_SEQUENCE =B.SEQ
AND TYPE='IDC'
AND METHOD='W'
AND ALLOCATION_SEQUENCE ='5358'
GROUP BY CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC


--DC

SELECT CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC,SUM(AMOUNT) FROM ALLOCATION_RESULTS_202109 A, VW_ALLOCATION_CONFIG B
WHERE A.ALLOCATION_SEQUENCE =B.SEQ
AND TYPE LIKE 'DC%FI%'
AND METHOD='W'
AND ALLOCATION_SEQUENCE IN (4110,4112,4114,4115,4116)
GROUP BY CUSTOMER_ID ,CONTRACT_ID ,RECEIVE_OUC,RECEIVE_SBU,SOURCE_OUC
ORDER BY RECEIVE_SBU DESC



-- Query for DC cost

SELECT  MGT_LINE, MGT_LINE_DESCRIPTION,VISION_OUC,SUM(BALANCE_09) FROM MGT_RESULT_2021
WHERE VISION_OUC IN (
SELECT OUC FROM OUC_NARROW
WHERE OUC_ATTRIBUTE_LEVEL=20
AND OUC_ATTRIBUTE IN ('OA124510','OA124520')) -- Input Segment In OA12 + Last 4 Digit
AND MGT_TYPE=60
AND RESULT_SOURCE IN ('FIN','MGT')
AND BAL_TYPE=3
AND BALANCE_09<>0
GROUP BY VISION_OUC,MGT_LINE, MGT_LINE_DESCRIPTION


